---

- name: '[Pretask] Install pip'
  hosts: all
  tasks:
    - name: Install required packages
      become: true
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - python-pip


# From: https://git.digitales.cslabrecha.org/ansible-roles/docker
- name: '[Pretask] Install docker'
  hosts: all
  roles:
    - role: docker


- name: Deploy the docker image managed by a systemd service
  hosts: all
  vars:
    docker_data_directories:
      - "/root/docker/hello-world/data"
    service_name: hello-world
    docker_image: hello-world
    docker_command: /usr/bin/docker run --rm -i --name "{{ service_name }}" "{{ docker_image }}"
  roles:
    - role: generic_docker_systemd
